/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantovan.progettonuovo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luana
 */
public class Prodotti extends javax.swing.JPanel {
    Connection conn;
    /**
     * Creates new form Prodotti
     */
    public Prodotti(Connection conn) {
        initComponents();
        this.conn = conn;
        riempiTabella();
    }
    public void riempiTabella(){
        String prodottiQuery = "SELECT NOME, PREZZO, QUANTITA, BARCODE FROM PRODOTTO_NEGOZIO";
        try{
            Statement stmt = this.conn.createStatement();
            ResultSet rs = stmt.executeQuery(prodottiQuery);
            DefaultTableModel model = (DefaultTableModel) prodottiTable.getModel();
            model.setRowCount(0);
            while(rs.next()){
                String b = rs.getString("BARCODE");
                String s = rs.getString("NOME");
                double t = rs.getDouble("PREZZO");
                DecimalFormat df = new DecimalFormat("#.00");
                int q = rs.getInt("QUANTITA");   
                model.addRow(new Object[]{b, s, df.format(t), q});
            }
        }
        catch(SQLException se){
            se.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prodottiTable = new javax.swing.JTable();

        prodottiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Barcode", "Nome", "Prezzo", "Quantità"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodottiTable.setMaximumSize(new java.awt.Dimension(2147483647, 260000));
        prodottiTable.setMinimumSize(new java.awt.Dimension(60, 0));
        prodottiTable.setPreferredSize(new java.awt.Dimension(375, 263));
        jScrollPane1.setViewportView(prodottiTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prodottiTable;
    // End of variables declaration//GEN-END:variables
}
