/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantovan.progettonuovo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luana
 */
public class Prodotti extends javax.swing.JPanel {
    Connection conn;
    /**
     * Creates new form Prodotti
     */
    public Prodotti(Connection conn) {
        initComponents();
        this.conn = conn;
        riempiTabella();
    }
    
    public void svuotaLista(){
        prodottiList.setModel(new DefaultListModel());
    }
    public void riempiTabella(){
        String prodottiQuery = "SELECT NOME, PREZZO, QUANTITA, BARCODE FROM PRODOTTO_NEGOZIO";
        try{
            Statement stmt = this.conn.createStatement();
            ResultSet rs = stmt.executeQuery(prodottiQuery);
            DefaultTableModel model = (DefaultTableModel) prodottiTable.getModel();
            model.setRowCount(0);
            while(rs.next()){
                String b = rs.getString("BARCODE");
                String s = rs.getString("NOME");
                double t = rs.getDouble("PREZZO");
                DecimalFormat df = new DecimalFormat("#.00");
                int q = rs.getInt("QUANTITA");   
                model.addRow(new Object[]{b, s, df.format(t), q});
            }
            prodottiTable.setModel(model);
        }
        catch(SQLException se){
            se.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prodottiTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        prodottiList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        prodottiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Nome", "Prezzo", "Quantità"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodottiTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prodottiTable.setMaximumSize(new java.awt.Dimension(2147483647, 260000));
        prodottiTable.setPreferredSize(new java.awt.Dimension(375, 263));
        prodottiTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        prodottiTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        prodottiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodottiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prodottiTable);

        prodottiList.setOpaque(false);
        prodottiList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        prodottiList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(prodottiList);

        jLabel1.setText("Dettagli prodotto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prodottiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodottiTableMouseClicked
        String query = "SELECT * FROM PRODOTTO_NEGOZIO WHERE BARCODE = '" + prodottiTable.getModel().getValueAt(prodottiTable.getSelectedRow(), 0) + "'";
        try{
            Statement stmt = this.conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            DefaultListModel model = new DefaultListModel();           
            while(rs.next()){
                String b = rs.getString("BARCODE");
                String s = rs.getString("NOME");
                String tg = rs.getString("TAGLIA");
                String m = rs.getString("MATERIALE");                
                double t = rs.getDouble("PREZZO");
                DecimalFormat df = new DecimalFormat("#.00");
                int q = rs.getInt("QUANTITA");
                model.addElement("BARCODE: " + b);
                model.addElement("NOME: " + s);
                model.addElement("TAGLIA: " + tg);
                model.addElement("MATERIALE: " + m);
                model.addElement("QUANTITA': " + q);
                model.addElement("PREZZO: " + df.format(t));                
            }
            prodottiList.setModel(model);
        }
        catch(SQLException se){
            se.printStackTrace();
        }
    }//GEN-LAST:event_prodottiTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> prodottiList;
    private javax.swing.JTable prodottiTable;
    // End of variables declaration//GEN-END:variables
}
